### ISSUE TITLE
Could be able to avoid business validation?

### ISSUE THREAD

**Issue by jmirc** [netceteragroup/valdr-bean-validation#11]
The validationRules json contains front-end and business rules. For example I have a User JPA which contains some contraints related to spring security tokens. These contraints are used by the backend but not at the front-end level.

It could be great to be able to avoid specific contraints from the validationRules.

**Comment by jgribonvald** [comment]
@jmirc & @philippd have you an example of project working with a jhipster project ? I'm trying to integrate valdr but i do'nt know where I'm wrong i'm getting such error

**Comment by jgribonvald** [comment]
I've found my problem, sorry for that...

I'm working with angular 1.2.x not 1.3 and Firefox provide a better error log
