### ISSUE TITLE
Custom Annotations Not working

### ISSUE THREAD

**Issue by conalryan** [netceteragroup/valdr-bean-validation#25]
I can't get the custom annotations to work.  Including the example on the demo project.  org.hibernate.validator.constraints.CreditCardNumber.

<code>
package com.springapp.mvc.controller;

import com.springapp.mvc.config.ValdrConfig;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import java.io.IOException;

@RestController
public class ValdrController {

    @RequestMapping(value = "/validationrules", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
    public String validateAll() throws IOException {

        return ValdrConfig.fetchValidationRules();
    }
}
</code>
<code>
package com.springapp.mvc.config;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Configuration;
import com.github.valdr.ConstraintParser;
import com.github.valdr.Options;

@Configuration
public class ValdrConfig {

    public ValdrConfig() { }

    public static String fetchValidationRules() throws IOException {

        // JSON response output content
        String jsonResponse;

        // Valdr Constraint Parser
        ConstraintParser parser;

        // Configuration options to be loaded ---------------------------------
        final Options options =  new Options();

        InputStream inputStream = new FileInputStream("src/main/resources/valdr.properties");
        Properties valdrProperties = new Properties();
        valdrProperties.load(inputStream);

        List<String> modelPackageList = new ArrayList<>();
        for (final String name: valdrProperties.stringPropertyNames()) {
            modelPackageList.add(valdrProperties.getProperty(name));
        }

        final List<String> modelPackages = new ArrayList<String>(
                Arrays.asList(modelPackageList.get(0).split(",")));

        options.setModelPackages(modelPackages);

        // Create parser object based on configuration options
        parser = new ConstraintParser(options);

        // response
        jsonResponse = parser.parse();
        return jsonResponse;
    }
}
</code>

<code>
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.springapp.mvn</groupId>
    <artifactId>Spring-First</artifactId>
    <version>0.1.0</version>
    <packaging>war</packaging>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.2.2.RELEASE</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        
        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <version>1.1.0.Final</version>
        </dependency>

        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-validator</artifactId>
            <version>5.1.3.Final</version>
        </dependency>

        <dependency>
            <groupId>com.github.valdr</groupId>
            <artifactId>valdr-bean-validation</artifactId>
            <version>1.1.0</version>
        </dependency>

        
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <version>4.1.5.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>

    </dependencies>

    <properties>
        <java.version>1.7</java.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>spring-releases</id>
            <url>https://repo.spring.io/libs-release</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>spring-releases</id>
            <url>https://repo.spring.io/libs-release</url>
        </pluginRepository>
    </pluginRepositories>
</project>
</code>

valdr.properties file:

valdr.model.packages=com.springapp.mvc.model,com.springapp.mvc.modeltwo

valdri-bean-validation.json file:

{
  "modelPackages": ["com.springapp.mvc.model"],
  "excludedClasses": ["com.springapp.mvc.model.IgnoredClass"],
  "excludedFields": ["com.springapp.mvc.model.Person#ignoredField"],
  "customAnnotationClasses": ["org.hibernate.validator.constraints.CreditCardNumber"],
  "corsAllowOriginPattern": "*",
  "outputFile": "${project.build.directory}/${project.build.finalName}/constraints.json"
}

Json printed to screen:

{
  "Greeting" : {
    "content" : {
      "required" : {
        "message" : "requried"
      }
    }
  },
  "PersonClass" : {
    "lastName" : {
      "size" : {
        "message" : "{javax.validation.constraints.Size.message}",
        "min" : 4,
        "max" : 31
      }
    },
    "ignoredField" : {
      "required" : {
        "message" : "{javax.validation.constraints.NotNull.message}"
      }
    },
    "withMoreBackslashes" : {
      "pattern" : {
        "message" : "{javax.validation.constraints.Pattern.message}",
        "flags" : [ ],
        "regexp" : "/\\\\abc\\./"
      }
    },
    "addSlashPrefixSuffix" : {
      "pattern" : {
        "message" : "{javax.validation.constraints.Pattern.message}",
        "flags" : [ ],
        "regexp" : "/abc/"
      }
    },
    "withBackslashes" : {
      "pattern" : {
        "message" : "{javax.validation.constraints.Pattern.message}",
        "flags" : [ ],
        "regexp" : "/\\abc\\./"
      }
    },
    "firstName" : {
      "required" : {
        "message" : "\\foo"
      }
    },
    "url" : {
      "hibernateUrl" : {
        "port" : -1,
        "message" : "{org.hibernate.validator.constraints.URL.message}",
        "protocol" : "",
        "host" : "",
        "flags" : [ ],
        "regexp" : ".*"
      }
    }
  },
  "IgnoredClass" : {
    "name" : {
      "required" : {
        "message" : "{javax.validation.constraints.NotNull.message}"
      }
    }
  }
}

**Comment by marcelstoer** [comment]
Thanks for using valdr. You shouldn't be opening issues for support requests, particularly if the problem seems related to your setup rather than this project itself (assumption because not even our demo works for you). Use our [Stackoverflow tag](https://github.com/netceteragroup/valdr-bean-validation#support) for support.
