### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by marcelstoer** [netceteragroup/valdr-bean-validation#48]
It's been almost 5y since the last release. A couple of fixes and dependency upgrades landed on master in the meantime: https://github.com/netceteragroup/valdr-bean-validation/compare/valdr-bean-validation-parent-1.1.3...master.

- bump the version to 2.0.0 since we're now requiring Java 17
- release from master

**Comment by velinovskav** [comment]
The release [2.0.0](https://github.com/netceteragroup/valdr-bean-validation/releases/tag/valdr-bean-validation-parent-2.0.0) was published.
